### ISSUE TITLE
如何验证sworker已经成功升级到s-worker-b

### ISSUE THREAD

**Issue by ws1214921** [crustio/crust-node#138]
按照官方公众号升级操作，https://mp.weixin.qq.com/s/hnVrDbllNsg82ort05fEjw
操作指令：sudo crust tools sworker-ab-upgrade
显示信息为：
Start sworker A/B upgragde....
Read configurations success.
sWorker code on chain: 0128bc5c89883eda0a75474b5bb07f806671a8a9423185066ded7ffa30339e60
sWorker self code: 0128bc5c89883eda0a75474b5bb07f806671a8a9423185066ded7ffa30339e60
sWorker is already latest
请问这个代表已经升级成功了吗？

**Comment by LowEntropyBody** [comment]
yes, sWorker has been upgraded successfully
